export { default as AboutPage } from './AboutPage'
export { default as NotFound } from './NotFound'
export { default as AlbumPage } from './AlbumPage'
export { default as Home } from './Home'
export { default as Login } from './Login'
